"""remove default from milestone order field

Revision ID: 04c06991cf98
Revises: 9ee261875120
Create Date: 2025-11-08 15:18:13.849411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c06991cf98'
down_revision: Union[str, None] = '9ee261875120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('milestones', 'order',
               existing_type=sa.INTEGER(),
               comment='Display order for drag-drop sorting (auto-assigned on creation)',
               existing_comment='Display order for drag-drop sorting',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('milestones', 'order',
               existing_type=sa.INTEGER(),
               comment='Display order for drag-drop sorting',
               existing_comment='Display order for drag-drop sorting (auto-assigned on creation)',
               existing_nullable=False)
    # ### end Alembic commands ###