"""add database system models

Revision ID: 1486390ee9b8
Revises: 80d0d1bfae70
Create Date: 2025-11-19 08:21:58.918339

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1486390ee9b8"
down_revision: Union[str, None] = "80d0d1bfae70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "databases",
        sa.Column("project_id", sa.Uuid(), nullable=False, comment="Foreign key to owning project"),
        sa.Column("name", sa.String(length=200), nullable=False, comment="Database display name"),
        sa.Column("description", sa.Text(), nullable=True, comment="Optional detailed description"),
        sa.Column("icon", sa.String(length=50), nullable=True, comment="Optional emoji icon"),
        sa.Column("color", sa.String(length=20), nullable=True, comment="Optional hex color code"),
        sa.Column(
            "is_template", sa.Boolean(), nullable=False, comment="Whether this is a template"
        ),
        sa.Column(
            "template_id",
            sa.Uuid(),
            nullable=True,
            comment="Reference to template if created from one",
        ),
        sa.Column(
            "created_by_user_id",
            sa.Uuid(),
            nullable=False,
            comment="UUID of user who created this database",
        ),
        sa.Column(
            "is_archived", sa.Boolean(), nullable=False, comment="Whether database is archived"
        ),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when database was archived",
        ),
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary key UUID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["template_id"], ["databases.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_database_project_created", "databases", ["project_id", "created_at"], unique=False
    )
    op.create_index("ix_database_project_name", "databases", ["project_id", "name"], unique=False)
    op.create_index("ix_database_template", "databases", ["is_template"], unique=False)
    op.create_index("ix_database_template_id", "databases", ["template_id"], unique=False)
    op.create_index(
        op.f("ix_databases_created_by_user_id"), "databases", ["created_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_databases_is_archived"), "databases", ["is_archived"], unique=False)
    op.create_index(op.f("ix_databases_project_id"), "databases", ["project_id"], unique=False)
    op.create_index(op.f("ix_databases_template_id"), "databases", ["template_id"], unique=False)
    op.create_index(
        "uq_database_project_name",
        "databases",
        ["project_id", "name"],
        unique=True,
        postgresql_where="is_archived = false",
    )
    op.create_table(
        "database_entries",
        sa.Column(
            "database_id", sa.Uuid(), nullable=False, comment="Foreign key to owning database"
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
            comment="Display order for manual sorting (0-based)",
        ),
        sa.Column(
            "created_by_user_id",
            sa.Uuid(),
            nullable=False,
            comment="UUID of user who created this entry",
        ),
        sa.Column(
            "last_edited_by_user_id",
            sa.Uuid(),
            nullable=False,
            comment="UUID of user who last edited this entry",
        ),
        sa.Column(
            "last_edited_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when entry was last edited",
        ),
        sa.Column("is_archived", sa.Boolean(), nullable=False, comment="Whether entry is archived"),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when entry was archived",
        ),
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary key UUID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["database_id"], ["databases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["last_edited_by_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_database_entries_created_by_user_id"),
        "database_entries",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_database_entries_database_id"), "database_entries", ["database_id"], unique=False
    )
    op.create_index(
        op.f("ix_database_entries_last_edited_by_user_id"),
        "database_entries",
        ["last_edited_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_entry_creator_created",
        "database_entries",
        ["created_by_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_entry_database_created", "database_entries", ["database_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_entry_database_position", "database_entries", ["database_id", "position"], unique=False
    )
    op.create_table(
        "database_properties",
        sa.Column(
            "database_id", sa.Uuid(), nullable=False, comment="Foreign key to owning database"
        ),
        sa.Column("name", sa.String(length=200), nullable=False, comment="Property display name"),
        sa.Column(
            "property_type",
            sa.String(length=50),
            nullable=False,
            comment=(
                "Property type: text, number, select, multiselect, date, checkbox, "
                "url, email, phone, formula, rollup, relation, created_time, created_by, "
                "last_edited_time, last_edited_by"
            ),
        ),
        sa.Column(
            "config", sa.JSON(), nullable=True, comment="Type-specific configuration in JSON format"
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
            comment="Display order for column positioning (0-based)",
        ),
        sa.Column(
            "is_required",
            sa.Boolean(),
            nullable=False,
            comment="Whether this property requires a value",
        ),
        sa.Column(
            "is_visible",
            sa.Boolean(),
            nullable=False,
            comment="Whether this property is visible by default",
        ),
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary key UUID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.CheckConstraint("position >= 0", name="ck_property_position"),
        sa.ForeignKeyConstraint(["database_id"], ["databases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("database_id", "name", name="uq_property_database_name"),
    )
    op.create_index(
        op.f("ix_database_properties_database_id"),
        "database_properties",
        ["database_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_database_properties_property_type"),
        "database_properties",
        ["property_type"],
        unique=False,
    )
    op.create_index(
        "ix_property_database_position",
        "database_properties",
        ["database_id", "position"],
        unique=False,
    )
    op.create_index(
        "ix_property_database_type",
        "database_properties",
        ["database_id", "property_type"],
        unique=False,
    )
    op.create_table(
        "database_views",
        sa.Column(
            "database_id", sa.Uuid(), nullable=False, comment="Foreign key to owning database"
        ),
        sa.Column("name", sa.String(length=200), nullable=False, comment="View display name"),
        sa.Column(
            "view_type",
            sa.String(length=50),
            nullable=False,
            comment="View type: table, board, calendar, list, gallery, timeline",
        ),
        sa.Column(
            "config",
            sa.JSON(),
            nullable=False,
            comment="View-specific configuration in JSON format",
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
            comment="Display order for view tabs (0-based)",
        ),
        sa.Column(
            "is_default", sa.Boolean(), nullable=False, comment="Whether this is the default view"
        ),
        sa.Column(
            "created_by_user_id",
            sa.Uuid(),
            nullable=False,
            comment="UUID of user who created this view",
        ),
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary key UUID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.CheckConstraint("position >= 0", name="ck_view_position"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["database_id"], ["databases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("database_id", "name", name="uq_view_database_name"),
    )
    op.create_index(
        op.f("ix_database_views_created_by_user_id"),
        "database_views",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_database_views_database_id"), "database_views", ["database_id"], unique=False
    )
    op.create_index(
        op.f("ix_database_views_is_default"), "database_views", ["is_default"], unique=False
    )
    op.create_index(
        "ix_view_database_default", "database_views", ["database_id", "is_default"], unique=False
    )
    op.create_index(
        "ix_view_database_position", "database_views", ["database_id", "position"], unique=False
    )
    op.create_table(
        "database_entry_values",
        sa.Column(
            "entry_id", sa.Uuid(), nullable=False, comment="Foreign key to database entry (row)"
        ),
        sa.Column(
            "property_id",
            sa.Uuid(),
            nullable=False,
            comment="Foreign key to database property (column)",
        ),
        sa.Column("value", sa.JSON(), nullable=True, comment="Property value in JSON format"),
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary key UUID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["entry_id"], ["database_entries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["property_id"], ["database_properties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id", "property_id", name="uq_entry_value_entry_property"),
    )
    op.create_index(
        op.f("ix_database_entry_values_entry_id"),
        "database_entry_values",
        ["entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_database_entry_values_property_id"),
        "database_entry_values",
        ["property_id"],
        unique=False,
    )
    op.create_index(
        "ix_entry_value_property", "database_entry_values", ["property_id"], unique=False
    )
    op.drop_index("ix_file_last_modified", table_name="files")
    op.create_index(
        "ix_file_last_modified",
        "files",
        ["last_modified_at"],
        unique=False,
        postgresql_ops={"last_modified_at": "DESC"},
    )
    op.drop_index("ix_commit_committed_at", table_name="git_commits")
    op.create_index(
        "ix_commit_committed_at",
        "git_commits",
        ["committed_at"],
        unique=False,
        postgresql_ops={"committed_at": "DESC"},
    )
    op.drop_index("ix_webhook_received", table_name="github_webhook_deliveries")
    op.create_index(
        "ix_webhook_received",
        "github_webhook_deliveries",
        ["received_at"],
        unique=False,
        postgresql_ops={"received_at": "DESC"},
    )
    op.drop_index("ix_pr_created", table_name="pull_requests")
    op.create_index(
        "ix_pr_created",
        "pull_requests",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_pr_created", table_name="pull_requests", postgresql_ops={"created_at": "DESC"}
    )
    op.create_index("ix_pr_created", "pull_requests", [sa.text("created_at DESC")], unique=False)
    op.drop_index(
        "ix_webhook_received",
        table_name="github_webhook_deliveries",
        postgresql_ops={"received_at": "DESC"},
    )
    op.create_index(
        "ix_webhook_received",
        "github_webhook_deliveries",
        [sa.text("received_at DESC")],
        unique=False,
    )
    op.drop_index(
        "ix_commit_committed_at", table_name="git_commits", postgresql_ops={"committed_at": "DESC"}
    )
    op.create_index(
        "ix_commit_committed_at", "git_commits", [sa.text("committed_at DESC")], unique=False
    )
    op.drop_index(
        "ix_file_last_modified", table_name="files", postgresql_ops={"last_modified_at": "DESC"}
    )
    op.create_index(
        "ix_file_last_modified", "files", [sa.text("last_modified_at DESC")], unique=False
    )
    op.drop_index("ix_entry_value_property", table_name="database_entry_values")
    op.drop_index(op.f("ix_database_entry_values_property_id"), table_name="database_entry_values")
    op.drop_index(op.f("ix_database_entry_values_entry_id"), table_name="database_entry_values")
    op.drop_table("database_entry_values")
    op.drop_index("ix_view_database_position", table_name="database_views")
    op.drop_index("ix_view_database_default", table_name="database_views")
    op.drop_index(op.f("ix_database_views_is_default"), table_name="database_views")
    op.drop_index(op.f("ix_database_views_database_id"), table_name="database_views")
    op.drop_index(op.f("ix_database_views_created_by_user_id"), table_name="database_views")
    op.drop_table("database_views")
    op.drop_index("ix_property_database_type", table_name="database_properties")
    op.drop_index("ix_property_database_position", table_name="database_properties")
    op.drop_index(op.f("ix_database_properties_property_type"), table_name="database_properties")
    op.drop_index(op.f("ix_database_properties_database_id"), table_name="database_properties")
    op.drop_table("database_properties")
    op.drop_index("ix_entry_database_position", table_name="database_entries")
    op.drop_index("ix_entry_database_created", table_name="database_entries")
    op.drop_index("ix_entry_creator_created", table_name="database_entries")
    op.drop_index(op.f("ix_database_entries_last_edited_by_user_id"), table_name="database_entries")
    op.drop_index(op.f("ix_database_entries_database_id"), table_name="database_entries")
    op.drop_index(op.f("ix_database_entries_created_by_user_id"), table_name="database_entries")
    op.drop_table("database_entries")
    op.drop_index(
        "uq_database_project_name", table_name="databases", postgresql_where="is_archived = false"
    )
    op.drop_index(op.f("ix_databases_template_id"), table_name="databases")
    op.drop_index(op.f("ix_databases_project_id"), table_name="databases")
    op.drop_index(op.f("ix_databases_is_archived"), table_name="databases")
    op.drop_index(op.f("ix_databases_created_by_user_id"), table_name="databases")
    op.drop_index("ix_database_template_id", table_name="databases")
    op.drop_index("ix_database_template", table_name="databases")
    op.drop_index("ix_database_project_name", table_name="databases")
    op.drop_index("ix_database_project_created", table_name="databases")
    op.drop_table("databases")
    # ### end Alembic commands ###
