"""add_git_and_file_models

Revision ID: 1fb7c46f33c8
Revises: dcca79a04cb7
Create Date: 2025-11-16 14:53:41.187501

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1fb7c46f33c8"
down_revision: Union[str, None] = "dcca79a04cb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("project_id", sa.UUID(), nullable=False, comment="Project this file belongs to"),
        sa.Column(
            "path",
            sa.String(length=1024),
            nullable=False,
            comment="Relative path from project root (e.g., 'src/main.py')",
        ),
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Filename only (e.g., 'main.py')"
        ),
        sa.Column(
            "extension",
            sa.String(length=50),
            nullable=True,
            comment="File extension (e.g., '.py', '.md', '.json')",
        ),
        sa.Column(
            "file_type",
            sa.String(length=20),
            nullable=False,
            comment="Classification: code, doc, config, test, asset, other",
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=True,
            comment="Full content for text files <1MB, null for larger/binary files",
        ),
        sa.Column(
            "content_hash",
            sa.String(length=64),
            nullable=True,
            comment="SHA-256 hash of content for change detection",
        ),
        sa.Column("size_bytes", sa.Integer(), nullable=False, comment="File size in bytes"),
        sa.Column(
            "encoding",
            sa.String(length=50),
            nullable=False,
            comment="Text encoding (default: utf-8)",
        ),
        sa.Column(
            "last_commit_sha",
            sa.String(length=40),
            nullable=True,
            comment="Full git commit hash that last modified this file",
        ),
        sa.Column(
            "last_commit_message",
            sa.String(length=500),
            nullable=True,
            comment="Commit message from last modification",
        ),
        sa.Column(
            "last_modified_by_user_id",
            sa.UUID(),
            nullable=True,
            comment="Ardha user who made the last commit",
        ),
        sa.Column(
            "last_modified_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp from git commit",
        ),
        sa.Column(
            "language",
            sa.String(length=50),
            nullable=True,
            comment="Detected programming language (e.g., 'python', 'javascript')",
        ),
        sa.Column(
            "is_binary", sa.Boolean(), nullable=False, comment="Whether file is binary (not text)"
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, comment="Soft delete flag"),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when soft deleted",
        ),
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary key UUID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.CheckConstraint(
            "file_type IN ('code', 'doc', 'config', 'test', 'asset', 'other')", name="ck_file_type"
        ),
        sa.CheckConstraint("size_bytes >= 0", name="ck_file_size_bytes"),
        sa.ForeignKeyConstraint(["last_modified_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "path", name="uq_file_project_path"),
    )
    op.create_index(
        "ix_file_last_modified",
        "files",
        ["last_modified_at"],
        unique=False,
        postgresql_ops={"last_modified_at": "DESC"},
    )
    op.create_index("ix_file_project_type", "files", ["project_id", "file_type"], unique=False)
    op.create_index(op.f("ix_files_extension"), "files", ["extension"], unique=False)
    op.create_index(op.f("ix_files_file_type"), "files", ["file_type"], unique=False)
    op.create_index(op.f("ix_files_is_deleted"), "files", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_files_language"), "files", ["language"], unique=False)
    op.create_index(op.f("ix_files_last_modified_at"), "files", ["last_modified_at"], unique=False)
    op.create_index(op.f("ix_files_project_id"), "files", ["project_id"], unique=False)
    op.create_table(
        "git_commits",
        sa.Column(
            "project_id", sa.UUID(), nullable=False, comment="Project this commit belongs to"
        ),
        sa.Column(
            "sha", sa.String(length=40), nullable=False, comment="Full git commit hash (40 chars)"
        ),
        sa.Column(
            "short_sha",
            sa.String(length=7),
            nullable=False,
            comment="Short commit hash (first 7 chars)",
        ),
        sa.Column("message", sa.Text(), nullable=False, comment="Full commit message"),
        sa.Column("author_name", sa.String(length=255), nullable=False, comment="Git author name"),
        sa.Column(
            "author_email", sa.String(length=255), nullable=False, comment="Git author email"
        ),
        sa.Column(
            "committed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Git commit timestamp",
        ),
        sa.Column(
            "pushed_at", sa.DateTime(timezone=True), nullable=True, comment="When pushed to remote"
        ),
        sa.Column(
            "branch", sa.String(length=255), nullable=False, comment="Branch name when committed"
        ),
        sa.Column(
            "is_merge", sa.Boolean(), nullable=False, comment="Whether this is a merge commit"
        ),
        sa.Column("parent_shas", sa.JSON(), nullable=True, comment="List of parent commit SHAs"),
        sa.Column("files_changed", sa.Integer(), nullable=False, comment="Number of files changed"),
        sa.Column("insertions", sa.Integer(), nullable=False, comment="Total lines added"),
        sa.Column("deletions", sa.Integer(), nullable=False, comment="Total lines deleted"),
        sa.Column(
            "linked_task_ids",
            sa.JSON(),
            nullable=True,
            comment="List of task IDs extracted from message (e.g., ['TAS-001', 'TAS-002'])",
        ),
        sa.Column(
            "closes_task_ids",
            sa.JSON(),
            nullable=True,
            comment="Tasks that are closed by this commit",
        ),
        sa.Column(
            "ardha_user_id", sa.UUID(), nullable=True, comment="Mapped Ardha user from git author"
        ),
        sa.Column(
            "synced_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Last sync with git repository",
        ),
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary key UUID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.CheckConstraint("deletions >= 0", name="ck_commit_deletions"),
        sa.CheckConstraint("files_changed >= 0", name="ck_commit_files_changed"),
        sa.CheckConstraint("insertions >= 0", name="ck_commit_insertions"),
        sa.ForeignKeyConstraint(["ardha_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "sha", name="uq_commit_project_sha"),
    )
    op.create_index(
        "ix_commit_committed_at",
        "git_commits",
        ["committed_at"],
        unique=False,
        postgresql_ops={"committed_at": "DESC"},
    )
    op.create_index(
        "ix_commit_project_branch", "git_commits", ["project_id", "branch"], unique=False
    )
    op.create_index(
        op.f("ix_git_commits_ardha_user_id"), "git_commits", ["ardha_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_git_commits_author_email"), "git_commits", ["author_email"], unique=False
    )
    op.create_index(op.f("ix_git_commits_branch"), "git_commits", ["branch"], unique=False)
    op.create_index(
        op.f("ix_git_commits_committed_at"), "git_commits", ["committed_at"], unique=False
    )
    op.create_index(op.f("ix_git_commits_project_id"), "git_commits", ["project_id"], unique=False)
    op.create_table(
        "file_commits",
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("commit_id", sa.UUID(), nullable=False),
        sa.Column(
            "change_type",
            sa.String(length=20),
            nullable=False,
            comment="Type of change: added, modified, deleted, renamed",
        ),
        sa.Column(
            "old_path",
            sa.String(length=1024),
            nullable=True,
            comment="Original path for renamed files",
        ),
        sa.Column("insertions", sa.Integer(), nullable=False, comment="Lines added in this file"),
        sa.Column("deletions", sa.Integer(), nullable=False, comment="Lines removed in this file"),
        sa.ForeignKeyConstraint(["commit_id"], ["git_commits.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id", "commit_id"),
    )
    op.create_index("ix_file_commits_change_type", "file_commits", ["change_type"], unique=False)
    op.create_index("ix_file_commits_commit", "file_commits", ["commit_id"], unique=False)
    op.create_table(
        "task_commits",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("commit_id", sa.UUID(), nullable=False),
        sa.Column(
            "linked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this link was created",
        ),
        sa.Column(
            "link_type",
            sa.String(length=20),
            nullable=False,
            comment="Type of link: mentioned, closes, fixes, implements",
        ),
        sa.ForeignKeyConstraint(["commit_id"], ["git_commits.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "commit_id"),
    )
    op.add_column(
        "tasks",
        sa.Column(
            "related_commit_shas",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
            comment="Array of git commit SHAs (legacy, use related_commits relationship)",
        ),
    )
    op.drop_column("tasks", "related_commits")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "related_commits",
            postgresql.ARRAY(sa.VARCHAR()),
            server_default=sa.text("'{}'::character varying[]"),
            autoincrement=False,
            nullable=False,
            comment="Array of git commit SHAs",
        ),
    )
    op.drop_column("tasks", "related_commit_shas")
    op.drop_table("task_commits")
    op.drop_index("ix_file_commits_commit", table_name="file_commits")
    op.drop_index("ix_file_commits_change_type", table_name="file_commits")
    op.drop_table("file_commits")
    op.drop_index(op.f("ix_git_commits_project_id"), table_name="git_commits")
    op.drop_index(op.f("ix_git_commits_committed_at"), table_name="git_commits")
    op.drop_index(op.f("ix_git_commits_branch"), table_name="git_commits")
    op.drop_index(op.f("ix_git_commits_author_email"), table_name="git_commits")
    op.drop_index(op.f("ix_git_commits_ardha_user_id"), table_name="git_commits")
    op.drop_index("ix_commit_project_branch", table_name="git_commits")
    op.drop_index(
        "ix_commit_committed_at", table_name="git_commits", postgresql_ops={"committed_at": "DESC"}
    )
    op.drop_table("git_commits")
    op.drop_index(op.f("ix_files_project_id"), table_name="files")
    op.drop_index(op.f("ix_files_last_modified_at"), table_name="files")
    op.drop_index(op.f("ix_files_language"), table_name="files")
    op.drop_index(op.f("ix_files_is_deleted"), table_name="files")
    op.drop_index(op.f("ix_files_file_type"), table_name="files")
    op.drop_index(op.f("ix_files_extension"), table_name="files")
    op.drop_index("ix_file_project_type", table_name="files")
    op.drop_index(
        "ix_file_last_modified", table_name="files", postgresql_ops={"last_modified_at": "DESC"}
    )
    op.drop_table("files")
    # ### end Alembic commands ###
