"""add_notification_system

Revision ID: 33d711c094a5
Revises: 606c1d22f358
Create Date: 2025-11-24 13:07:03.640087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33d711c094a5'
down_revision: Union[str, None] = '606c1d22f358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who owns these preferences'),
    sa.Column('email_enabled', sa.Boolean(), nullable=False, comment='Enable email notifications globally'),
    sa.Column('push_enabled', sa.Boolean(), nullable=False, comment='Enable push notifications globally'),
    sa.Column('task_assigned', sa.Boolean(), nullable=False, comment='Notify when assigned to task'),
    sa.Column('task_completed', sa.Boolean(), nullable=False, comment='Notify when assigned task is completed'),
    sa.Column('task_overdue', sa.Boolean(), nullable=False, comment='Notify about overdue tasks'),
    sa.Column('mentions', sa.Boolean(), nullable=False, comment='Notify when mentioned in comments/chat'),
    sa.Column('project_invites', sa.Boolean(), nullable=False, comment='Notify when invited to project'),
    sa.Column('database_updates', sa.Boolean(), nullable=False, comment='Notify about database changes'),
    sa.Column('system_notifications', sa.Boolean(), nullable=False, comment='Notify about system-wide announcements'),
    sa.Column('email_frequency', sa.String(length=20), nullable=False, comment='Email frequency: instant, daily, weekly, never'),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True, comment='Start of quiet hours (no notifications)'),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True, comment='End of quiet hours'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When preferences were created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='When preferences were last updated'),
    sa.CheckConstraint("email_frequency IN ('instant', 'daily', 'weekly', 'never')", name='ck_notification_preference_email_frequency'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_notification_preference_user')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who receives this notification'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Notification type: task_assigned, task_completed, etc.'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Short notification title'),
    sa.Column('message', sa.Text(), nullable=False, comment='Main notification message (max 1000 chars)'),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Additional context data in JSON format'),
    sa.Column('link_type', sa.String(length=50), nullable=True, comment='Type of linked entity: task, project, database, chat'),
    sa.Column('link_id', sa.UUID(), nullable=True, comment='UUID of linked entity'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Whether notification has been read'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='When notification was marked as read'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When notification was created'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When notification should be auto-deleted'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.CheckConstraint("link_type IS NULL OR link_type IN ('task', 'project', 'database', 'chat')", name='ck_notification_link_type'),
    sa.CheckConstraint("type IN ('task_assigned', 'task_completed', 'task_overdue', 'mention', 'project_invite', 'database_update', 'system')", name='ck_notification_type'),
    sa.CheckConstraint('length(message) <= 1000', name='ck_notification_message_length'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.drop_index('ix_file_last_modified', table_name='files')
    op.create_index('ix_file_last_modified', 'files', ['last_modified_at'], unique=False, postgresql_ops={'last_modified_at': 'DESC'})
    op.drop_index('ix_commit_committed_at', table_name='git_commits')
    op.create_index('ix_commit_committed_at', 'git_commits', ['committed_at'], unique=False, postgresql_ops={'committed_at': 'DESC'})
    op.drop_index('ix_webhook_received', table_name='github_webhook_deliveries')
    op.create_index('ix_webhook_received', 'github_webhook_deliveries', ['received_at'], unique=False, postgresql_ops={'received_at': 'DESC'})
    op.drop_index('ix_pr_created', table_name='pull_requests')
    op.create_index('ix_pr_created', 'pull_requests', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pr_created', table_name='pull_requests', postgresql_ops={'created_at': 'DESC'})
    op.create_index('ix_pr_created', 'pull_requests', [sa.text('created_at DESC')], unique=False)
    op.drop_index('ix_webhook_received', table_name='github_webhook_deliveries', postgresql_ops={'received_at': 'DESC'})
    op.create_index('ix_webhook_received', 'github_webhook_deliveries', [sa.text('received_at DESC')], unique=False)
    op.drop_index('ix_commit_committed_at', table_name='git_commits', postgresql_ops={'committed_at': 'DESC'})
    op.create_index('ix_commit_committed_at', 'git_commits', [sa.text('committed_at DESC')], unique=False)
    op.drop_index('ix_file_last_modified', table_name='files', postgresql_ops={'last_modified_at': 'DESC'})
    op.create_index('ix_file_last_modified', 'files', [sa.text('last_modified_at DESC')], unique=False)
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
