"""remove unique constraint from milestone order

Revision ID: 3fbba54b25d7
Revises: 04c06991cf98
Create Date: 2025-11-08 15:22:58.529914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fbba54b25d7'
down_revision: Union[str, None] = '04c06991cf98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_milestone_project_order', 'milestones', type_='unique')
    op.create_index('ix_milestone_project_order', 'milestones', ['project_id', 'order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_milestone_project_order', table_name='milestones')
    op.create_unique_constraint('uq_milestone_project_order', 'milestones', ['project_id', 'order'])
    # ### end Alembic commands ###