"""add database system models

Revision ID: 436d6f22de59
Revises: 1486390ee9b8
Create Date: 2025-11-19 09:51:07.507007

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "436d6f22de59"
down_revision: Union[str, None] = "1486390ee9b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_file_last_modified", table_name="files")
    op.create_index(
        "ix_file_last_modified",
        "files",
        ["last_modified_at"],
        unique=False,
        postgresql_ops={"last_modified_at": "DESC"},
    )
    op.drop_index("ix_commit_committed_at", table_name="git_commits")
    op.create_index(
        "ix_commit_committed_at",
        "git_commits",
        ["committed_at"],
        unique=False,
        postgresql_ops={"committed_at": "DESC"},
    )
    op.drop_index("ix_webhook_received", table_name="github_webhook_deliveries")
    op.create_index(
        "ix_webhook_received",
        "github_webhook_deliveries",
        ["received_at"],
        unique=False,
        postgresql_ops={"received_at": "DESC"},
    )
    op.drop_index("ix_pr_created", table_name="pull_requests")
    op.create_index(
        "ix_pr_created",
        "pull_requests",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_pr_created", table_name="pull_requests", postgresql_ops={"created_at": "DESC"}
    )
    op.create_index("ix_pr_created", "pull_requests", [sa.text("created_at DESC")], unique=False)
    op.drop_index(
        "ix_webhook_received",
        table_name="github_webhook_deliveries",
        postgresql_ops={"received_at": "DESC"},
    )
    op.create_index(
        "ix_webhook_received",
        "github_webhook_deliveries",
        [sa.text("received_at DESC")],
        unique=False,
    )
    op.drop_index(
        "ix_commit_committed_at", table_name="git_commits", postgresql_ops={"committed_at": "DESC"}
    )
    op.create_index(
        "ix_commit_committed_at", "git_commits", [sa.text("committed_at DESC")], unique=False
    )
    op.drop_index(
        "ix_file_last_modified", table_name="files", postgresql_ops={"last_modified_at": "DESC"}
    )
    op.create_index(
        "ix_file_last_modified", "files", [sa.text("last_modified_at DESC")], unique=False
    )
    # ### end Alembic commands ###
