"""add chat models with messages and ai usage

Revision ID: 56c4a4a45b08
Revises: 3fbba54b25d7
Create Date: 2025-11-09 14:07:17.873169

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56c4a4a45b08"
down_revision: Union[str, None] = "3fbba54b25d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_usage",
        sa.Column(
            "model_name", sa.String(length=100), nullable=False, comment="Name of AI model used"
        ),
        sa.Column(
            "operation",
            sa.String(length=20),
            nullable=False,
            comment="Type of AI operation performed",
        ),
        sa.Column(
            "tokens_input", sa.Integer(), nullable=False, comment="Number of input tokens consumed"
        ),
        sa.Column(
            "tokens_output",
            sa.Integer(),
            nullable=False,
            comment="Number of output tokens generated",
        ),
        sa.Column(
            "cost",
            sa.Numeric(precision=10, scale=6),
            nullable=False,
            comment="Cost of the operation",
        ),
        sa.Column(
            "usage_date", sa.Date(), nullable=False, comment="Date for daily aggregation queries"
        ),
        sa.Column(
            "user_id", sa.Uuid(), nullable=False, comment="UUID of user who performed the operation"
        ),
        sa.Column(
            "project_id",
            sa.Uuid(),
            nullable=True,
            comment="UUID of associated project (nullable for personal operations)",
        ),
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary key UUID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_usage_model_name"), "ai_usage", ["model_name"], unique=False)
    op.create_index(op.f("ix_ai_usage_operation"), "ai_usage", ["operation"], unique=False)
    op.create_index(op.f("ix_ai_usage_project_id"), "ai_usage", ["project_id"], unique=False)
    op.create_index(
        "ix_ai_usage_project_id_date",
        "ai_usage",
        ["project_id", sa.text("usage_date DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_ai_usage_usage_date"), "ai_usage", ["usage_date"], unique=False)
    op.create_index(op.f("ix_ai_usage_user_id"), "ai_usage", ["user_id"], unique=False)
    op.create_index(
        "ix_ai_usage_user_id_date",
        "ai_usage",
        ["user_id", sa.text("usage_date DESC")],
        unique=False,
    )
    op.create_table(
        "chats",
        sa.Column(
            "title",
            sa.String(length=200),
            nullable=False,
            comment="Auto-generated chat title from first message",
        ),
        sa.Column("mode", sa.String(length=20), nullable=False, comment="AI interaction mode"),
        sa.Column("context", sa.JSON(), nullable=False, comment="Conversation context and state"),
        sa.Column(
            "total_tokens",
            sa.Integer(),
            nullable=False,
            comment="Cumulative token count for the entire chat",
        ),
        sa.Column(
            "total_cost",
            sa.Numeric(precision=10, scale=6),
            nullable=False,
            comment="Cumulative cost for the entire chat",
        ),
        sa.Column("is_archived", sa.Boolean(), nullable=False, comment="Whether chat is archived"),
        sa.Column(
            "project_id",
            sa.Uuid(),
            nullable=True,
            comment="UUID of associated project (nullable for personal chats)",
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False, comment="UUID of user who owns the chat"),
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary key UUID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chats_is_archived"), "chats", ["is_archived"], unique=False)
    op.create_index(op.f("ix_chats_project_id"), "chats", ["project_id"], unique=False)
    op.create_index(
        "ix_chats_project_id_created_at",
        "chats",
        ["project_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_chats_user_id"), "chats", ["user_id"], unique=False)
    op.create_index(
        "ix_chats_user_id_created_at",
        "chats",
        ["user_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column(
            "role",
            sa.String(length=10),
            nullable=False,
            comment="Message role (user, assistant, system)",
        ),
        sa.Column("content", sa.Text(), nullable=False, comment="Message content"),
        sa.Column(
            "model_used",
            sa.String(length=100),
            nullable=True,
            comment="AI model name used for assistant messages",
        ),
        sa.Column(
            "tokens_input",
            sa.Integer(),
            nullable=True,
            comment="Input tokens for AI-generated messages",
        ),
        sa.Column(
            "tokens_output",
            sa.Integer(),
            nullable=True,
            comment="Output tokens for AI-generated messages",
        ),
        sa.Column(
            "cost",
            sa.Numeric(precision=10, scale=6),
            nullable=True,
            comment="Cost for AI-generated messages",
        ),
        sa.Column(
            "message_metadata",
            sa.JSON(),
            nullable=False,
            comment="JSON for tool calls, reasoning, and other AI data",
        ),
        sa.Column("chat_id", sa.Uuid(), nullable=False, comment="UUID of parent chat conversation"),
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary key UUID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_chat_id"), "messages", ["chat_id"], unique=False)
    op.create_index(
        "ix_messages_chat_id_created_at",
        "messages",
        ["chat_id", sa.text("created_at ASC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_chat_id_created_at", table_name="messages")
    op.drop_index(op.f("ix_messages_chat_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_chats_user_id_created_at", table_name="chats")
    op.drop_index(op.f("ix_chats_user_id"), table_name="chats")
    op.drop_index("ix_chats_project_id_created_at", table_name="chats")
    op.drop_index(op.f("ix_chats_project_id"), table_name="chats")
    op.drop_index(op.f("ix_chats_is_archived"), table_name="chats")
    op.drop_table("chats")
    op.drop_index("ix_ai_usage_user_id_date", table_name="ai_usage")
    op.drop_index(op.f("ix_ai_usage_user_id"), table_name="ai_usage")
    op.drop_index(op.f("ix_ai_usage_usage_date"), table_name="ai_usage")
    op.drop_index("ix_ai_usage_project_id_date", table_name="ai_usage")
    op.drop_index(op.f("ix_ai_usage_project_id"), table_name="ai_usage")
    op.drop_index(op.f("ix_ai_usage_operation"), table_name="ai_usage")
    op.drop_index(op.f("ix_ai_usage_model_name"), table_name="ai_usage")
    op.drop_table("ai_usage")
    # ### end Alembic commands ###
