"""add_github_integration_models

Revision ID: 80d0d1bfae70
Revises: 1fb7c46f33c8
Create Date: 2025-11-18 07:37:45.312212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d0d1bfae70'
down_revision: Union[str, None] = '1fb7c46f33c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_integrations',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Foreign key to associated project (one-to-one)'),
    sa.Column('repository_owner', sa.String(length=255), nullable=False, comment='GitHub username or organization name'),
    sa.Column('repository_name', sa.String(length=255), nullable=False, comment='Repository name'),
    sa.Column('repository_url', sa.String(length=512), nullable=False, comment='Full GitHub repository URL'),
    sa.Column('default_branch', sa.String(length=255), nullable=False, comment='Default branch name'),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False, comment='Encrypted OAuth access token'),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True, comment='OAuth token expiration timestamp'),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True, comment='Encrypted refresh token for token renewal'),
    sa.Column('installation_id', sa.BigInteger(), nullable=True, comment='GitHub App installation ID (if using GitHub Apps)'),
    sa.Column('auto_create_pr', sa.Boolean(), nullable=False, comment='Automatically create PRs from commits'),
    sa.Column('auto_link_tasks', sa.Boolean(), nullable=False, comment='Automatically link tasks from commit messages'),
    sa.Column('require_review', sa.Boolean(), nullable=False, comment='Enforce PR review requirements'),
    sa.Column('branch_protection_enabled', sa.Boolean(), nullable=False, comment='Whether branch protection is enabled'),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True, comment='Secret for webhook signature verification'),
    sa.Column('webhook_url', sa.String(length=512), nullable=True, comment='Registered webhook URL'),
    sa.Column('webhook_events', sa.JSON(), nullable=True, comment='List of subscribed webhook events'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether integration is active'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful sync timestamp'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Last sync error message'),
    sa.Column('connection_status', sa.String(length=20), nullable=False, comment='Connection state: connected, disconnected, error, unauthorized'),
    sa.Column('total_prs', sa.Integer(), nullable=False, comment='Total pull requests tracked'),
    sa.Column('merged_prs', sa.Integer(), nullable=False, comment='Merged pull request count'),
    sa.Column('closed_prs', sa.Integer(), nullable=False, comment='Closed pull request count'),
    sa.Column('webhook_events_received', sa.Integer(), nullable=False, comment='Total webhook events received'),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False, comment='User who created this integration'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.CheckConstraint("connection_status IN ('connected', 'disconnected', 'error', 'unauthorized')", name='ck_github_integration_connection_status'),
    sa.CheckConstraint('closed_prs >= 0', name='ck_github_integration_closed_prs'),
    sa.CheckConstraint('merged_prs >= 0', name='ck_github_integration_merged_prs'),
    sa.CheckConstraint('total_prs >= 0', name='ck_github_integration_total_prs'),
    sa.CheckConstraint('webhook_events_received >= 0', name='ck_github_integration_webhook_events_received'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_github_integration_project')
    )
    op.create_index('ix_github_integration_repository', 'github_integrations', ['repository_owner', 'repository_name'], unique=False)
    op.create_index('ix_github_integration_status', 'github_integrations', ['connection_status'], unique=False)
    op.create_index(op.f('ix_github_integrations_connection_status'), 'github_integrations', ['connection_status'], unique=False)
    op.create_index(op.f('ix_github_integrations_created_by_user_id'), 'github_integrations', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_github_integrations_installation_id'), 'github_integrations', ['installation_id'], unique=False)
    op.create_index(op.f('ix_github_integrations_is_active'), 'github_integrations', ['is_active'], unique=False)
    op.create_index(op.f('ix_github_integrations_project_id'), 'github_integrations', ['project_id'], unique=True)
    op.create_index(op.f('ix_github_integrations_repository_name'), 'github_integrations', ['repository_name'], unique=False)
    op.create_index(op.f('ix_github_integrations_repository_owner'), 'github_integrations', ['repository_owner'], unique=False)
    op.create_table('github_webhook_deliveries',
    sa.Column('github_integration_id', sa.UUID(), nullable=False, comment='Foreign key to GitHub integration'),
    sa.Column('delivery_id', sa.String(length=255), nullable=False, comment="GitHub's delivery UUID"),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment="Type of webhook event (e.g., 'pull_request', 'push', 'check_suite')"),
    sa.Column('action', sa.String(length=100), nullable=True, comment="Event action (e.g., 'opened', 'closed', 'synchronize')"),
    sa.Column('payload', sa.JSON(), nullable=False, comment='Full webhook payload for replay and debugging'),
    sa.Column('payload_size', sa.Integer(), nullable=False, comment='Payload size in bytes'),
    sa.Column('headers', sa.JSON(), nullable=True, comment='Request headers as JSON'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Processing status: pending, processing, processed, failed, ignored'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='When webhook was processed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment="Processing error message if status is 'failed'"),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of processing retry attempts'),
    sa.Column('signature', sa.String(length=255), nullable=True, comment='X-Hub-Signature-256 header value'),
    sa.Column('signature_verified', sa.Boolean(), nullable=False, comment='Whether signature was successfully verified'),
    sa.Column('pr_number', sa.Integer(), nullable=True, comment='Related PR number (if event related to PR)'),
    sa.Column('commit_sha', sa.String(length=40), nullable=True, comment='Related commit SHA (if event related to commit)'),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True, comment='Type of related entity: pull_request, commit, check_run, review'),
    sa.Column('related_entity_id', sa.UUID(), nullable=True, comment='Ardha entity UUID (if mapped to internal entity)'),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When webhook was received'),
    sa.Column('processed_by', sa.String(length=255), nullable=True, comment='Worker/service that processed this webhook'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.CheckConstraint("related_entity_type IS NULL OR related_entity_type IN ('pull_request', 'commit', 'check_run', 'review')", name='ck_webhook_entity_type'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'processed', 'failed', 'ignored')", name='ck_webhook_status'),
    sa.CheckConstraint('payload_size >= 0', name='ck_webhook_payload_size'),
    sa.CheckConstraint('retry_count >= 0', name='ck_webhook_retry_count'),
    sa.ForeignKeyConstraint(['github_integration_id'], ['github_integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id', name='uq_webhook_delivery_id')
    )
    op.create_index(op.f('ix_github_webhook_deliveries_action'), 'github_webhook_deliveries', ['action'], unique=False)
    op.create_index(op.f('ix_github_webhook_deliveries_commit_sha'), 'github_webhook_deliveries', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_github_webhook_deliveries_delivery_id'), 'github_webhook_deliveries', ['delivery_id'], unique=True)
    op.create_index(op.f('ix_github_webhook_deliveries_event_type'), 'github_webhook_deliveries', ['event_type'], unique=False)
    op.create_index(op.f('ix_github_webhook_deliveries_github_integration_id'), 'github_webhook_deliveries', ['github_integration_id'], unique=False)
    op.create_index(op.f('ix_github_webhook_deliveries_pr_number'), 'github_webhook_deliveries', ['pr_number'], unique=False)
    op.create_index(op.f('ix_github_webhook_deliveries_received_at'), 'github_webhook_deliveries', ['received_at'], unique=False)
    op.create_index(op.f('ix_github_webhook_deliveries_related_entity_id'), 'github_webhook_deliveries', ['related_entity_id'], unique=False)
    op.create_index(op.f('ix_github_webhook_deliveries_related_entity_type'), 'github_webhook_deliveries', ['related_entity_type'], unique=False)
    op.create_index(op.f('ix_github_webhook_deliveries_signature_verified'), 'github_webhook_deliveries', ['signature_verified'], unique=False)
    op.create_index(op.f('ix_github_webhook_deliveries_status'), 'github_webhook_deliveries', ['status'], unique=False)
    op.create_index('ix_webhook_commit_sha', 'github_webhook_deliveries', ['commit_sha'], unique=False)
    op.create_index('ix_webhook_entity_type', 'github_webhook_deliveries', ['related_entity_type'], unique=False)
    op.create_index('ix_webhook_event_type', 'github_webhook_deliveries', ['event_type'], unique=False)
    op.create_index('ix_webhook_integration', 'github_webhook_deliveries', ['github_integration_id'], unique=False)
    op.create_index('ix_webhook_pr_number', 'github_webhook_deliveries', ['pr_number'], unique=False)
    op.create_index('ix_webhook_received', 'github_webhook_deliveries', ['received_at'], unique=False, postgresql_ops={'received_at': 'DESC'})
    op.create_index('ix_webhook_status', 'github_webhook_deliveries', ['status'], unique=False)
    op.create_table('pull_requests',
    sa.Column('github_integration_id', sa.UUID(), nullable=False, comment='Foreign key to GitHub integration'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Foreign key to project'),
    sa.Column('pr_number', sa.Integer(), nullable=False, comment='GitHub PR number'),
    sa.Column('github_pr_id', sa.BigInteger(), nullable=False, comment="GitHub's internal PR ID"),
    sa.Column('title', sa.String(length=500), nullable=False, comment='PR title'),
    sa.Column('description', sa.Text(), nullable=True, comment='PR description/body'),
    sa.Column('state', sa.String(length=20), nullable=False, comment='PR state: open, closed, merged, draft'),
    sa.Column('head_branch', sa.String(length=255), nullable=False, comment="Source branch (e.g., 'feature/new-feature')"),
    sa.Column('base_branch', sa.String(length=255), nullable=False, comment="Target branch (usually 'main')"),
    sa.Column('head_sha', sa.String(length=40), nullable=False, comment='Latest commit SHA in PR'),
    sa.Column('author_github_username', sa.String(length=255), nullable=False, comment="PR author's GitHub username"),
    sa.Column('author_user_id', sa.UUID(), nullable=True, comment='Mapped Ardha user ID'),
    sa.Column('is_draft', sa.Boolean(), nullable=False, comment='Whether PR is in draft state'),
    sa.Column('mergeable', sa.Boolean(), nullable=True, comment='Whether PR can be merged (null if not computed)'),
    sa.Column('merged', sa.Boolean(), nullable=False, comment='Whether PR has been merged'),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True, comment='Merge timestamp'),
    sa.Column('merged_by_github_username', sa.String(length=255), nullable=True, comment='GitHub username who merged the PR'),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True, comment='Close timestamp'),
    sa.Column('review_status', sa.String(length=30), nullable=False, comment='Review state: pending, approved, changes_requested, dismissed'),
    sa.Column('reviews_count', sa.Integer(), nullable=False, comment='Total review count'),
    sa.Column('approvals_count', sa.Integer(), nullable=False, comment='Approval count'),
    sa.Column('checks_status', sa.String(length=20), nullable=False, comment='CI/CD checks status: pending, success, failure, error, cancelled'),
    sa.Column('checks_count', sa.Integer(), nullable=False, comment='Total checks count'),
    sa.Column('required_checks_passed', sa.Boolean(), nullable=False, comment='Whether all required checks passed'),
    sa.Column('additions', sa.Integer(), nullable=False, comment='Lines added'),
    sa.Column('deletions', sa.Integer(), nullable=False, comment='Lines deleted'),
    sa.Column('changed_files', sa.Integer(), nullable=False, comment='Files changed count'),
    sa.Column('commits_count', sa.Integer(), nullable=False, comment='Commits in PR'),
    sa.Column('html_url', sa.String(length=512), nullable=False, comment='GitHub PR web URL'),
    sa.Column('api_url', sa.String(length=512), nullable=False, comment='GitHub API URL for this PR'),
    sa.Column('linked_task_ids', sa.JSON(), nullable=True, comment='List of task UUIDs mentioned in PR'),
    sa.Column('closes_task_ids', sa.JSON(), nullable=True, comment='Tasks that will close when PR merges'),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last sync with Ardha database'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.CheckConstraint("checks_status IN ('pending', 'success', 'failure', 'error', 'cancelled')", name='ck_pr_checks_status'),
    sa.CheckConstraint("review_status IN ('pending', 'approved', 'changes_requested', 'dismissed')", name='ck_pr_review_status'),
    sa.CheckConstraint("state IN ('open', 'closed', 'merged', 'draft')", name='ck_pr_state'),
    sa.CheckConstraint('additions >= 0', name='ck_pr_additions'),
    sa.CheckConstraint('approvals_count >= 0', name='ck_pr_approvals_count'),
    sa.CheckConstraint('changed_files >= 0', name='ck_pr_changed_files'),
    sa.CheckConstraint('checks_count >= 0', name='ck_pr_checks_count'),
    sa.CheckConstraint('commits_count >= 0', name='ck_pr_commits_count'),
    sa.CheckConstraint('deletions >= 0', name='ck_pr_deletions'),
    sa.CheckConstraint('pr_number > 0', name='ck_pr_number'),
    sa.CheckConstraint('reviews_count >= 0', name='ck_pr_reviews_count'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['github_integration_id'], ['github_integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_integration_id', 'pr_number', name='uq_pr_integration_number')
    )
    op.create_index('ix_pr_author', 'pull_requests', ['author_user_id'], unique=False)
    op.create_index('ix_pr_created', 'pull_requests', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('ix_pr_draft', 'pull_requests', ['is_draft'], unique=False)
    op.create_index('ix_pr_merged', 'pull_requests', ['merged'], unique=False)
    op.create_index('ix_pr_project', 'pull_requests', ['project_id'], unique=False)
    op.create_index('ix_pr_state', 'pull_requests', ['state'], unique=False)
    op.create_index(op.f('ix_pull_requests_author_github_username'), 'pull_requests', ['author_github_username'], unique=False)
    op.create_index(op.f('ix_pull_requests_author_user_id'), 'pull_requests', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_base_branch'), 'pull_requests', ['base_branch'], unique=False)
    op.create_index(op.f('ix_pull_requests_checks_status'), 'pull_requests', ['checks_status'], unique=False)
    op.create_index(op.f('ix_pull_requests_github_integration_id'), 'pull_requests', ['github_integration_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_github_pr_id'), 'pull_requests', ['github_pr_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_head_branch'), 'pull_requests', ['head_branch'], unique=False)
    op.create_index(op.f('ix_pull_requests_head_sha'), 'pull_requests', ['head_sha'], unique=False)
    op.create_index(op.f('ix_pull_requests_is_draft'), 'pull_requests', ['is_draft'], unique=False)
    op.create_index(op.f('ix_pull_requests_merged'), 'pull_requests', ['merged'], unique=False)
    op.create_index(op.f('ix_pull_requests_pr_number'), 'pull_requests', ['pr_number'], unique=False)
    op.create_index(op.f('ix_pull_requests_project_id'), 'pull_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_review_status'), 'pull_requests', ['review_status'], unique=False)
    op.create_index(op.f('ix_pull_requests_state'), 'pull_requests', ['state'], unique=False)
    op.create_table('pr_commits',
    sa.Column('pr_id', sa.UUID(), nullable=False),
    sa.Column('commit_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False, comment='Order of this commit in the PR'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this commit was added to the PR'),
    sa.ForeignKeyConstraint(['commit_id'], ['git_commits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pr_id', 'commit_id')
    )
    op.create_index('ix_pr_commits_commit', 'pr_commits', ['commit_id'], unique=False)
    op.create_index('ix_pr_commits_position', 'pr_commits', ['position'], unique=False)
    op.create_index('ix_pr_commits_pr', 'pr_commits', ['pr_id'], unique=False)
    op.create_table('pr_tasks',
    sa.Column('pr_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(length=20), nullable=False, comment='Type of link: mentioned, implements, closes, related'),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this link was created'),
    sa.Column('linked_from', sa.String(length=50), nullable=False, comment='Source of link: commit_message, pr_description, pr_comment'),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pr_id', 'task_id')
    )
    op.create_index('ix_pr_tasks_link_type', 'pr_tasks', ['link_type'], unique=False)
    op.create_index('ix_pr_tasks_pr', 'pr_tasks', ['pr_id'], unique=False)
    op.create_index('ix_pr_tasks_task', 'pr_tasks', ['task_id'], unique=False)
    op.drop_index('ix_file_last_modified', table_name='files')
    op.create_index('ix_file_last_modified', 'files', ['last_modified_at'], unique=False, postgresql_ops={'last_modified_at': 'DESC'})
    op.drop_index('ix_commit_committed_at', table_name='git_commits')
    op.create_index('ix_commit_committed_at', 'git_commits', ['committed_at'], unique=False, postgresql_ops={'committed_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commit_committed_at', table_name='git_commits', postgresql_ops={'committed_at': 'DESC'})
    op.create_index('ix_commit_committed_at', 'git_commits', [sa.text('committed_at DESC')], unique=False)
    op.drop_index('ix_file_last_modified', table_name='files', postgresql_ops={'last_modified_at': 'DESC'})
    op.create_index('ix_file_last_modified', 'files', [sa.text('last_modified_at DESC')], unique=False)
    op.drop_index('ix_pr_tasks_task', table_name='pr_tasks')
    op.drop_index('ix_pr_tasks_pr', table_name='pr_tasks')
    op.drop_index('ix_pr_tasks_link_type', table_name='pr_tasks')
    op.drop_table('pr_tasks')
    op.drop_index('ix_pr_commits_pr', table_name='pr_commits')
    op.drop_index('ix_pr_commits_position', table_name='pr_commits')
    op.drop_index('ix_pr_commits_commit', table_name='pr_commits')
    op.drop_table('pr_commits')
    op.drop_index(op.f('ix_pull_requests_state'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_review_status'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_project_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_pr_number'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_merged'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_is_draft'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_head_sha'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_head_branch'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_github_pr_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_github_integration_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_checks_status'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_base_branch'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_author_user_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_author_github_username'), table_name='pull_requests')
    op.drop_index('ix_pr_state', table_name='pull_requests')
    op.drop_index('ix_pr_project', table_name='pull_requests')
    op.drop_index('ix_pr_merged', table_name='pull_requests')
    op.drop_index('ix_pr_draft', table_name='pull_requests')
    op.drop_index('ix_pr_created', table_name='pull_requests', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('ix_pr_author', table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index('ix_webhook_status', table_name='github_webhook_deliveries')
    op.drop_index('ix_webhook_received', table_name='github_webhook_deliveries', postgresql_ops={'received_at': 'DESC'})
    op.drop_index('ix_webhook_pr_number', table_name='github_webhook_deliveries')
    op.drop_index('ix_webhook_integration', table_name='github_webhook_deliveries')
    op.drop_index('ix_webhook_event_type', table_name='github_webhook_deliveries')
    op.drop_index('ix_webhook_entity_type', table_name='github_webhook_deliveries')
    op.drop_index('ix_webhook_commit_sha', table_name='github_webhook_deliveries')
    op.drop_index(op.f('ix_github_webhook_deliveries_status'), table_name='github_webhook_deliveries')
    op.drop_index(op.f('ix_github_webhook_deliveries_signature_verified'), table_name='github_webhook_deliveries')
    op.drop_index(op.f('ix_github_webhook_deliveries_related_entity_type'), table_name='github_webhook_deliveries')
    op.drop_index(op.f('ix_github_webhook_deliveries_related_entity_id'), table_name='github_webhook_deliveries')
    op.drop_index(op.f('ix_github_webhook_deliveries_received_at'), table_name='github_webhook_deliveries')
    op.drop_index(op.f('ix_github_webhook_deliveries_pr_number'), table_name='github_webhook_deliveries')
    op.drop_index(op.f('ix_github_webhook_deliveries_github_integration_id'), table_name='github_webhook_deliveries')
    op.drop_index(op.f('ix_github_webhook_deliveries_event_type'), table_name='github_webhook_deliveries')
    op.drop_index(op.f('ix_github_webhook_deliveries_delivery_id'), table_name='github_webhook_deliveries')
    op.drop_index(op.f('ix_github_webhook_deliveries_commit_sha'), table_name='github_webhook_deliveries')
    op.drop_index(op.f('ix_github_webhook_deliveries_action'), table_name='github_webhook_deliveries')
    op.drop_table('github_webhook_deliveries')
    op.drop_index(op.f('ix_github_integrations_repository_owner'), table_name='github_integrations')
    op.drop_index(op.f('ix_github_integrations_repository_name'), table_name='github_integrations')
    op.drop_index(op.f('ix_github_integrations_project_id'), table_name='github_integrations')
    op.drop_index(op.f('ix_github_integrations_is_active'), table_name='github_integrations')
    op.drop_index(op.f('ix_github_integrations_installation_id'), table_name='github_integrations')
    op.drop_index(op.f('ix_github_integrations_created_by_user_id'), table_name='github_integrations')
    op.drop_index(op.f('ix_github_integrations_connection_status'), table_name='github_integrations')
    op.drop_index('ix_github_integration_status', table_name='github_integrations')
    op.drop_index('ix_github_integration_repository', table_name='github_integrations')
    op.drop_table('github_integrations')
    # ### end Alembic commands ###
