"""add milestones table

Revision ID: 9ee261875120
Revises: d843b8a8385a
Create Date: 2025-11-08 14:56:13.091465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee261875120'
down_revision: Union[str, None] = 'd843b8a8385a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestones',
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Foreign key to owning project'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Milestone display name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional detailed description'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: not_started, in_progress, completed, cancelled'),
    sa.Column('color', sa.String(length=7), nullable=False, comment='Hex color code for UI display (e.g., #3b82f6)'),
    sa.Column('progress_percentage', sa.Integer(), nullable=False, comment='Progress 0-100, calculated from task completion'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True, comment='Optional start date'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True, comment='Optional target completion date'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when status changed to completed'),
    sa.Column('order', sa.Integer(), nullable=False, comment='Display order for drag-drop sorting'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.CheckConstraint("color ~ '^#[0-9A-Fa-f]{6}$'", name='ck_milestone_color'),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'completed', 'cancelled')", name='ck_milestone_status'),
    sa.CheckConstraint('"order" >= 0', name='ck_milestone_order'),
    sa.CheckConstraint('progress_percentage >= 0 AND progress_percentage <= 100', name='ck_milestone_progress'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'order', name='uq_milestone_project_order')
    )
    op.create_index('ix_milestone_due_date', 'milestones', ['due_date'], unique=False)
    op.create_index(op.f('ix_milestones_due_date'), 'milestones', ['due_date'], unique=False)
    op.create_index(op.f('ix_milestones_project_id'), 'milestones', ['project_id'], unique=False)
    op.create_index(op.f('ix_milestones_status'), 'milestones', ['status'], unique=False)
    op.create_foreign_key(None, 'tasks', 'milestones', ['milestone_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_milestones_status'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_project_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_due_date'), table_name='milestones')
    op.drop_index('ix_milestone_due_date', table_name='milestones')
    op.drop_table('milestones')
    # ### end Alembic commands ###