"""Initial migration - users table

Revision ID: b4e31b4c9224
Revises: 
Create Date: 2025-11-07 18:56:20.726706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e31b4c9224'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address"),
    sa.Column('username', sa.String(length=50), nullable=False, comment="User's unique username"),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment="User's full display name"),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Hashed password (null for OAuth users)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the account is active'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Whether user has admin privileges'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment="URL to user's profile picture"),
    sa.Column('github_id', sa.String(length=100), nullable=True, comment='GitHub OAuth user ID'),
    sa.Column('google_id', sa.String(length=100), nullable=True, comment='Google OAuth user ID'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last successful login'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###