"""add memory models

Revision ID: b7dd91c3f022
Revises: 9fec61d55870
Create Date: 2025-11-14 08:29:02.500207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7dd91c3f022'
down_revision: Union[str, None] = '9fec61d55870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create memories table
    op.create_table('memories',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('summary', sa.String(length=200), nullable=False),
        sa.Column('qdrant_collection', sa.String(length=50), nullable=False),
        sa.Column('qdrant_point_id', sa.String(length=100), nullable=False),
        sa.Column('embedding_model', sa.String(length=100), nullable=False),
        sa.Column('memory_type', sa.String(length=50), nullable=False),
        sa.Column('source_type', sa.String(length=50), nullable=False),
        sa.Column('source_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('importance', sa.Integer(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('access_count', sa.Integer(), nullable=False),
        sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_archived', sa.Boolean(), nullable=False),
        sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for memories table
    op.create_index('ix_memories_user_id', 'memories', ['user_id'], unique=False)
    op.create_index('ix_memories_project_id', 'memories', ['project_id'], unique=False)
    op.create_index('ix_memories_qdrant_collection', 'memories', ['qdrant_collection'], unique=False)
    op.create_index('ix_memories_qdrant_point_id', 'memories', ['qdrant_point_id'], unique=True)
    op.create_index('ix_memories_memory_type', 'memories', ['memory_type'], unique=False)
    op.create_index('ix_memories_source_type', 'memories', ['source_type'], unique=False)
    op.create_index('ix_memories_source_id', 'memories', ['source_id'], unique=False)
    op.create_index('ix_memories_importance', 'memories', ['importance'], unique=False)
    op.create_index('ix_memories_last_accessed', 'memories', ['last_accessed'], unique=False)
    op.create_index('ix_memories_expires_at', 'memories', ['expires_at'], unique=False)
    op.create_index('ix_memories_is_archived', 'memories', ['is_archived'], unique=False)
    
    # Create composite indexes
    op.create_index('ix_memory_user_created', 'memories', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_memory_project_importance', 'memories', ['project_id', 'importance'], unique=False)
    op.create_index('ix_memory_type_user', 'memories', ['memory_type', 'user_id'], unique=False)
    op.create_index('ix_memory_expires', 'memories', ['expires_at'], unique=False)
    
    # Create memory_links table
    op.create_table('memory_links',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('memory_from_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('memory_to_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('relationship_type', sa.String(length=50), nullable=False),
        sa.Column('strength', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['memory_from_id'], ['memories.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['memory_to_id'], ['memories.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for memory_links table
    op.create_index('ix_memory_links_memory_from_id', 'memory_links', ['memory_from_id'], unique=False)
    op.create_index('ix_memory_links_memory_to_id', 'memory_links', ['memory_to_id'], unique=False)
    op.create_index('ix_memory_links_relationship_type', 'memory_links', ['relationship_type'], unique=False)
    
    # Create composite index for memory_links
    op.create_index('ix_memory_link_from_to', 'memory_links', ['memory_from_id', 'memory_to_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes first
    op.drop_index('ix_memory_link_from_to', table_name='memory_links')
    op.drop_index('ix_memory_links_relationship_type', table_name='memory_links')
    op.drop_index('ix_memory_links_memory_to_id', table_name='memory_links')
    op.drop_index('ix_memory_links_memory_from_id', table_name='memory_links')
    
    # Drop memory_links table
    op.drop_table('memory_links')
    
    # Drop composite indexes
    op.drop_index('ix_memory_expires', table_name='memories')
    op.drop_index('ix_memory_type_user', table_name='memories')
    op.drop_index('ix_memory_project_importance', table_name='memories')
    op.drop_index('ix_memory_user_created', table_name='memories')
    
    # Drop single column indexes
    op.drop_index('ix_memories_is_archived', table_name='memories')
    op.drop_index('ix_memories_expires_at', table_name='memories')
    op.drop_index('ix_memories_last_accessed', table_name='memories')
    op.drop_index('ix_memories_importance', table_name='memories')
    op.drop_index('ix_memories_source_id', table_name='memories')
    op.drop_index('ix_memories_source_type', table_name='memories')
    op.drop_index('ix_memories_memory_type', table_name='memories')
    op.drop_index('ix_memories_qdrant_point_id', table_name='memories')
    op.drop_index('ix_memories_qdrant_collection', table_name='memories')
    op.drop_index('ix_memories_project_id', table_name='memories')
    op.drop_index('ix_memories_user_id', table_name='memories')
    
    # Drop memories table
    op.drop_table('memories')
    
    # ### end Alembic commands ###