"""add task models with dependencies and tags

Revision ID: d843b8a8385a
Revises: fa93e28de77f
Create Date: 2025-11-08 12:29:14.618534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd843b8a8385a'
down_revision: Union[str, None] = 'fa93e28de77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment="Tag name (e.g., 'backend', 'high-priority')"),
    sa.Column('color', sa.String(length=7), nullable=False, comment='Hex color code for UI display'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_task_tag_project_name')
    )
    op.create_index(op.f('ix_task_tags_project_id'), 'task_tags', ['project_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False, comment='Auto-generated unique identifier like ARD-001, ARD-002'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Task status: todo, in_progress, in_review, done, cancelled'),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False, comment='User or AI that created this task'),
    sa.Column('phase', sa.String(length=100), nullable=True, comment="Development phase (e.g., 'Phase 1: Backend')"),
    sa.Column('milestone_id', sa.UUID(), nullable=True),
    sa.Column('epic', sa.String(length=255), nullable=True, comment='Epic/theme for grouping large features'),
    sa.Column('estimate_hours', sa.Float(), nullable=True),
    sa.Column('actual_hours', sa.Float(), nullable=True, comment='Tracked time spent on task'),
    sa.Column('complexity', sa.String(length=20), nullable=True, comment='Complexity: trivial, simple, medium, complex, very_complex'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='Priority: urgent, high, medium, low'),
    sa.Column('openspec_proposal_id', sa.UUID(), nullable=True, comment='Linked OpenSpec proposal'),
    sa.Column('openspec_change_path', sa.String(length=500), nullable=True, comment='Path to openspec/changes/xxx/ directory'),
    sa.Column('ai_generated', sa.Boolean(), nullable=False, comment='Was this task created by AI?'),
    sa.Column('ai_confidence', sa.Float(), nullable=True, comment='AI confidence score (0.0-1.0)'),
    sa.Column('ai_reasoning', sa.Text(), nullable=True, comment="AI's reasoning for creating this task"),
    sa.Column('related_commits', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False, comment='Array of git commit SHAs'),
    sa.Column('related_prs', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False, comment='Array of pull request URLs'),
    sa.Column('related_files', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False, comment='Array of file paths modified by this task'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='When status changed to in_progress'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When status changed to done'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.CheckConstraint("complexity IS NULL OR complexity IN ('trivial', 'simple', 'medium', 'complex', 'very_complex')", name='ck_task_complexity'),
    sa.CheckConstraint("priority IN ('urgent', 'high', 'medium', 'low')", name='ck_task_priority'),
    sa.CheckConstraint("status IN ('todo', 'in_progress', 'in_review', 'done', 'cancelled')", name='ck_task_status'),
    sa.CheckConstraint('actual_hours IS NULL OR actual_hours >= 0', name='ck_task_actual_hours'),
    sa.CheckConstraint('ai_confidence IS NULL OR (ai_confidence >= 0 AND ai_confidence <= 1)', name='ck_task_ai_confidence'),
    sa.CheckConstraint('estimate_hours IS NULL OR estimate_hours >= 0', name='ck_task_estimate_hours'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'identifier', name='uq_task_project_identifier')
    )
    op.create_index('ix_task_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('ix_task_status_priority', 'tasks', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_identifier'), 'tasks', ['identifier'], unique=False)
    op.create_index(op.f('ix_tasks_milestone_id'), 'tasks', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('task_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User who performed this action (null if AI)'),
    sa.Column('action', sa.String(length=100), nullable=False, comment="Action type (e.g., 'created', 'status_changed', 'assigned')"),
    sa.Column('old_value', sa.Text(), nullable=True, comment='Previous value (JSON string for complex types)'),
    sa.Column('new_value', sa.Text(), nullable=True, comment='New value (JSON string for complex types)'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Optional user comment explaining the change'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_activities_task_id'), 'task_activities', ['task_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='The task that has the dependency'),
    sa.Column('depends_on_task_id', sa.UUID(), nullable=False, comment='The task that must be completed first'),
    sa.Column('dependency_type', sa.String(length=20), nullable=False, comment='Type: blocks or depends_on'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name='uq_task_dependency_task_depends_on')
    )
    op.create_index(op.f('ix_task_dependencies_depends_on_task_id'), 'task_dependencies', ['depends_on_task_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_task_id'), 'task_dependencies', ['task_id'], unique=False)
    op.create_table('task_task_tags',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['task_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_task_tags')
    op.drop_index(op.f('ix_task_dependencies_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_depends_on_task_id'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_task_activities_task_id'), table_name='task_activities')
    op.drop_table('task_activities')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_milestone_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_identifier'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_index('ix_task_status_priority', table_name='tasks')
    op.drop_index('ix_task_due_date', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_task_tags_project_id'), table_name='task_tags')
    op.drop_table('task_tags')
    # ### end Alembic commands ###