"""add openspec proposals table

Revision ID: dcca79a04cb7
Revises: b7dd91c3f022
Create Date: 2025-11-15 09:37:51.356076

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dcca79a04cb7"
down_revision: Union[str, None] = "b7dd91c3f022"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "openspec_proposals",
        sa.Column("project_id", sa.Uuid(), nullable=False, comment="UUID of parent project"),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Unique proposal name within project",
        ),
        sa.Column(
            "directory_path",
            sa.String(length=512),
            nullable=False,
            comment="Full path to proposal directory (e.g., openspec/changes/xxx)",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="Proposal status: pending, approved, rejected, in_progress, "
            "completed, archived",
        ),
        sa.Column(
            "created_by_user_id",
            sa.Uuid(),
            nullable=False,
            comment="UUID of user who created the proposal",
        ),
        sa.Column(
            "proposal_content",
            sa.Text(),
            nullable=True,
            comment="Content of proposal.md file",
        ),
        sa.Column(
            "tasks_content",
            sa.Text(),
            nullable=True,
            comment="Content of tasks.md file",
        ),
        sa.Column(
            "spec_delta_content",
            sa.Text(),
            nullable=True,
            comment="Content of spec-delta.md file",
        ),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Parsed metadata.json content",
        ),
        sa.Column(
            "approved_by_user_id",
            sa.Uuid(),
            nullable=True,
            comment="UUID of user who approved the proposal",
        ),
        sa.Column(
            "approved_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when proposal was approved",
        ),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when proposal was archived",
        ),
        sa.Column(
            "completion_percentage",
            sa.Integer(),
            nullable=False,
            comment="Progress percentage calculated from synced tasks (0-100)",
        ),
        sa.Column(
            "task_sync_status",
            sa.String(length=20),
            nullable=False,
            comment="Task sync status: not_synced, syncing, synced, sync_failed",
        ),
        sa.Column(
            "last_sync_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of last task synchronization",
        ),
        sa.Column(
            "sync_error_message",
            sa.Text(),
            nullable=True,
            comment="Error message from last sync operation",
        ),
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary key UUID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'in_progress', "
            "'completed', 'archived')",
            name="ck_openspec_status",
        ),
        sa.CheckConstraint(
            "task_sync_status IN ('not_synced', 'syncing', 'synced', 'sync_failed')",
            name="ck_openspec_task_sync_status",
        ),
        sa.CheckConstraint(
            "completion_percentage >= 0 AND completion_percentage <= 100",
            name="ck_openspec_completion_percentage",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["approved_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_openspec_project_name"),
    )
    op.create_index("ix_openspec_created_at", "openspec_proposals", ["created_at"], unique=False)
    op.create_index(
        "ix_openspec_project_status", "openspec_proposals", ["project_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_openspec_proposals_project_id"), "openspec_proposals", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_openspec_proposals_status"), "openspec_proposals", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_openspec_proposals_status"), table_name="openspec_proposals")
    op.drop_index(op.f("ix_openspec_proposals_project_id"), table_name="openspec_proposals")
    op.drop_index("ix_openspec_project_status", table_name="openspec_proposals")
    op.drop_index("ix_openspec_created_at", table_name="openspec_proposals")
    op.drop_table("openspec_proposals")
    # ### end Alembic commands ###
