"""add project and project_member tables

Revision ID: fa93e28de77f
Revises: b4e31b4c9224
Create Date: 2025-11-08 09:26:03.105239

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa93e28de77f"
down_revision: Union[str, None] = "b4e31b4c9224"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=255), nullable=False, comment="Project display name"),
        sa.Column("description", sa.Text(), nullable=True, comment="Project description"),
        sa.Column(
            "slug", sa.String(length=255), nullable=False, comment="URL-safe unique identifier"
        ),
        sa.Column("owner_id", sa.Uuid(), nullable=False, comment="UUID of the project owner"),
        sa.Column(
            "visibility",
            sa.String(length=50),
            nullable=False,
            comment="Access control level (private/team/public)",
        ),
        sa.Column("tech_stack", sa.JSON(), nullable=False, comment="JSON array of technology tags"),
        sa.Column(
            "git_repo_url", sa.String(length=500), nullable=True, comment="Git repository URL"
        ),
        sa.Column(
            "git_branch", sa.String(length=255), nullable=False, comment="Default Git branch name"
        ),
        sa.Column(
            "openspec_enabled", sa.Boolean(), nullable=False, comment="Whether OpenSpec is enabled"
        ),
        sa.Column(
            "openspec_path",
            sa.String(length=255),
            nullable=False,
            comment="Path to OpenSpec directory",
        ),
        sa.Column(
            "is_archived", sa.Boolean(), nullable=False, comment="Whether project is archived"
        ),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when project was archived",
        ),
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary key UUID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_is_archived"), "projects", ["is_archived"], unique=False)
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_index(op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False)
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    op.create_table(
        "project_members",
        sa.Column("project_id", sa.Uuid(), nullable=False, comment="UUID of the project"),
        sa.Column("user_id", sa.Uuid(), nullable=False, comment="UUID of the user"),
        sa.Column(
            "role",
            sa.String(length=50),
            nullable=False,
            comment="User's role in project (owner/admin/member/viewer)",
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when user joined project",
        ),
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary key UUID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when record was last updated",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "user_id", name="uq_project_user"),
    )
    op.create_index(
        op.f("ix_project_members_project_id"), "project_members", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_members_user_id"), "project_members", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_members_user_id"), table_name="project_members")
    op.drop_index(op.f("ix_project_members_project_id"), table_name="project_members")
    op.drop_table("project_members")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_index(op.f("ix_projects_is_archived"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
